<a href="https://colab.research.google.com/github/mcstllns/DeepLearning/blob/main/P09d_Ejercicio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicio

Crea una serie temporal con una regla y comprueba si una red RNN o LSTM pueden aprenderla

In [1]:
import numpy as np

# random is a function, doing random sampling in numpy.
X = np.random.randint(10, size=(100,3))

# the array will be having 20 elements.
print(X)

[[8 3 7]
 [6 5 4]
 [7 0 0]
 [9 1 7]
 [7 9 6]
 [1 5 2]
 [9 9 7]
 [7 2 8]
 [0 7 2]
 [5 4 0]
 [5 4 9]
 [6 6 8]
 [3 6 7]
 [1 9 0]
 [2 7 4]
 [0 0 7]
 [4 6 6]
 [6 1 8]
 [1 5 7]
 [2 7 6]
 [4 2 3]
 [1 9 4]
 [7 0 8]
 [6 4 1]
 [1 6 7]
 [5 7 1]
 [2 5 1]
 [2 9 0]
 [6 5 9]
 [3 5 8]
 [3 8 7]
 [7 6 5]
 [3 0 2]
 [1 5 6]
 [8 5 1]
 [8 2 8]
 [3 0 1]
 [9 1 2]
 [6 3 8]
 [6 4 4]
 [3 5 0]
 [1 5 0]
 [0 1 7]
 [1 5 9]
 [1 7 9]
 [3 1 6]
 [5 0 2]
 [6 5 7]
 [0 3 9]
 [3 6 3]
 [7 9 2]
 [9 1 9]
 [6 4 1]
 [9 9 4]
 [6 2 1]
 [3 2 3]
 [7 2 4]
 [9 1 4]
 [6 5 3]
 [0 4 8]
 [7 3 4]
 [8 6 8]
 [3 4 9]
 [7 9 4]
 [3 2 3]
 [7 3 0]
 [7 0 2]
 [6 1 2]
 [5 1 5]
 [0 9 1]
 [3 6 2]
 [5 0 5]
 [0 5 0]
 [8 2 5]
 [3 9 0]
 [9 2 3]
 [5 1 5]
 [1 5 6]
 [4 6 1]
 [7 3 6]
 [3 0 4]
 [8 1 6]
 [1 0 5]
 [1 8 8]
 [9 9 5]
 [5 3 3]
 [8 6 2]
 [3 2 6]
 [4 8 6]
 [6 9 8]
 [4 9 2]
 [6 1 7]
 [2 7 1]
 [3 9 3]
 [4 0 7]
 [1 7 3]
 [6 3 4]
 [5 4 5]
 [5 3 2]
 [4 3 8]]


In [2]:
Y = np.where(X[:,0] < 5, 0, 1)
print(Y)

[1 1 1 1 1 0 1 1 0 1 1 1 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0 0 1 0 0 1 0 0 1 1 0
 1 1 1 0 0 0 0 0 0 1 1 0 0 1 1 1 1 1 0 1 1 1 0 1 1 0 1 0 1 1 1 1 0 0 1 0 1
 0 1 1 0 0 1 0 1 0 0 1 1 1 0 0 1 0 1 0 0 0 0 1 1 1 0]


In [3]:
# determinamos el numero de casos para train y test
ratio = 0.8
n = int(ratio*X.shape[0])

# aleatorizamos los indices de las filas y elegimos los n primeros indices para train y los restantes para test
idx = np.random.permutation(X.shape[0])
training_idx, test_idx = idx[:n,], idx[n:]

# creamos las matrices de train y test
trainX = X[training_idx,:]
trainY = Y[training_idx]

testX = X[test_idx,:]
testY = Y[test_idx]


print(trainX, trainY)

[[2 9 0]
 [8 5 1]
 [6 3 8]
 [0 0 7]
 [6 4 4]
 [9 2 3]
 [9 1 2]
 [8 2 5]
 [8 1 6]
 [0 5 0]
 [2 5 1]
 [3 0 1]
 [3 5 0]
 [6 6 8]
 [3 6 7]
 [9 9 5]
 [7 3 4]
 [6 5 7]
 [4 8 6]
 [5 4 0]
 [2 7 4]
 [1 7 3]
 [6 1 2]
 [4 3 8]
 [9 1 9]
 [6 3 4]
 [6 9 8]
 [7 0 8]
 [3 8 7]
 [5 3 2]
 [1 9 4]
 [3 9 3]
 [4 6 6]
 [4 2 3]
 [1 5 2]
 [0 9 1]
 [3 4 9]
 [8 6 2]
 [3 6 2]
 [5 4 5]
 [0 4 8]
 [1 5 6]
 [5 0 2]
 [5 0 5]
 [3 1 6]
 [4 0 7]
 [0 1 7]
 [7 3 6]
 [6 4 1]
 [1 5 7]
 [7 9 6]
 [6 1 8]
 [6 5 3]
 [7 0 0]
 [1 8 8]
 [5 3 3]
 [6 2 1]
 [5 4 9]
 [3 2 3]
 [3 0 4]
 [7 3 0]
 [5 1 5]
 [2 7 1]
 [9 1 4]
 [6 5 4]
 [6 5 9]
 [7 9 4]
 [7 9 2]
 [8 2 8]
 [1 5 0]
 [9 1 7]
 [8 6 8]
 [1 5 9]
 [4 6 1]
 [7 2 8]
 [5 7 1]
 [3 5 8]
 [1 5 6]
 [3 6 3]
 [2 7 6]] [0 1 1 0 1 1 1 1 1 0 0 0 0 1 0 1 1 1 0 1 0 0 1 0 1 1 1 1 0 1 0 0 0 0 0 0 0
 1 0 1 0 0 1 1 0 0 0 1 1 0 1 1 1 1 0 1 1 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 0 0
 1 1 0 0 0 0]
